# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true

# Java
java.version=

# Mod - All field required.
mod.name=Female Gender Mod
mod.id=wildfire_gender
mod.group=com.wildfiregender.main
mod.version=5.0.0-Beta.4
mod.description=Adds extra customization options to the player model by adding breasts for a more feminine appearance
mod.license=LGPL-3.0
mod.source=https://github.com/FemaleGenderMod/FemaleGenderMod
mod.issue_tracker=https://github.com/FemaleGenderMod/FemaleGenderMod/issues

# Stonecutter
stonecutter_version=0.9.7
stonecutter_enabled_fabric_versions=26.1, 26.2
stonecutter_enabled_neoforge_versions=26.1, 26.2

# The below field are intentionally left blank,
# to edit, please edit gradle.properties for each versions.

# Minecraft
minecraft_version=

# Fabric https://fabricmc.net/versions.html
deps.fabric-loader=
deps.fabric-api=

# NeoForge https://projects.neoforged.net/neoforged/neoforge
deps.neoforge=
deps.min_neoforge=
deps.neo_form_version=

# Dependencies
deps.modmenu=
