pluginManagement {
    repositories {
        maven("https://maven.fabricmc.net/")
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("dev.kikugie.stonecutter") version "0.9.5"
}

stonecutter {
    // TODO(celeste) long term goal: eventually combine the fabric & neo (git) branches into one main branch
    // this could be done using stonecutter `branch()`es, with a project structure that looks similar to:
    //
    // : (root project, has no sources of its own)
    // └ :common (where the loader-independent code actually lives)
    //   ├ :fabric (fabric-specific code, branch `include()`s :common)
    //   │ ├ :fabric:26.1 (version-specific subprojects generated by stonecutter from the :fabric subproject)
    //   │ └ :fabric:26.2
    //   └ :neoforge (same as :fabric, but for neoforge)
    //     └ ...
    //
    // each branch would (unfortunately) need their own buildscripts though, although this is
    // definitely a lot easier now (at least on common) with the game being unobfuscated

    shared {
        version("26.1")
        version("26.2", "26.2-pre-6")
        vcsVersion = "26.2"
    }

    create(rootProject)
}
