stonecutter_enabled_platforms=fabric, neoforge

# Java
java.version=25

# Minecraft
minecraft_version=26.1.2

# Fabric
deps.fabric_loader=0.19.2
deps.fabric_api=0.144.3

# NeoForge
deps.neoforge=26.1.2.94
deps.min_neoforge=26.1.2.84
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
deps.neo_form_version=26.1.2-1

# Dependencies
deps.modmenu=18.0.0-alpha.6
