modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="wildfire_gender"
version="3.2.1"
displayName="Female Gender Mod (Fork)"
authors="Wildfire_Romeo"
description='''
NEOFORGE VERSION - The Female Gender Mod introduces extra player model customization options, including a unique feature.
'''

[[mixins]]
config="wildfire_gender.mixins.json"

[[dependencies.wildfire_gender]]
modId="neoforge"
type="required"
versionRange="[21.1.222,)"
ordering="NONE"
side="BOTH"

[[dependencies.wildfire_gender]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
